<?php

   /**
 * Template Name: Alarm and Monitoring Quote
 * Version: The Best
 * Description: Alarm and Monitoring Quote
 * Author: Cyber Spyder Marketing
 * Author URI: https://www.cyberspyder.net
 * Group: Cyber Spyder
 * License: GPLv2
 * Required PDF Version: 4.0
 * Tags: alarm, form, cyberspyder, insurance, quote
 */


/* Prevent direct access to the template (always good to include this) */
if ( ! class_exists( 'GFForms' ) ) {
	return;
}

/**
 * All Gravity PDF v4/v5/v6 templates have access to the following variables:
 *
 * @var array  $form      The current Gravity Form array
 * @var array  $entry     The raw entry data
 * @var array  $form_data The processed entry data stored in an array
 * @var object $settings  The current PDF configuration
 * @var array  $fields    An array of Gravity Form fields which can be accessed with their ID number
 * @var array  $config    The initialised template config class – eg. /config/zadani.php
 */

?>

<!-- Any PDF CSS styles can be placed in the style tag below -->
<style>

</style>

<!-- The PDF content should be placed in here -->
<table width="100%" cellpadding="5">
<tbody>
<tr>
<td style="width: 187px;"><img src="https://forms.dfainsure.com/wp-content/uploads/2024/01/DFAlogo-187x100.png" /></td>
<td style="text-align: right; width: 443px;">
<p>PO Box 1868<br />Rockwall, Texas 75087<br />P:(214)646-3347<br />F:(214)943-6531</p>
</td>
</tr>
</tbody>
</table>
<table width="100%" cellpadding="5">
<tbody>
<tr>
<td style="text-align: center;">
<h2>Alarm and Monitoring</h2>
</td>
</tr>
<tr>
<td style="text-align: center; width: 100%;background: #ffc10d;padding:10px;">
<h2>Section I - General Information</h2>
</td>
</tr>
<tr>
<td><strong>Applicant Legal Name (Including dba's):</strong>        {applicant_name:1}</td>
</tr>
<tr>
<td><strong>Name to appear on company licence:</strong>        {name_to_appear_on_company_license:2}</td>
</tr>
<tr>
<td><strong>Owner:</strong>        {owner:3}   <strong>Contact Person/Title:</strong>        {contact_person:4}</td>
</tr>
</tbody>
</table>
<table width="100%" cellpadding="5">
<tbody>
<tr>
<td><strong>Phone:</strong>        {phone:5}</td>
<td><strong>Fax:</strong>        {fax:6}</td>
<td><strong>Email Address:</strong>        {email_address:7}</td>
</tr>
</tbody>
</table>
<table width="100%" cellpadding="5">
<tbody>
<tr>
<td><strong>Mailing Address:</strong>   {Address (Street Address):8.1}, {Address (City):8.3}, {Address (State / Province / Region):8.4}  {Address (ZIP / Postal Code):8.5}</td>
</tr>
<tr>
<td><strong>Location Address:</strong>   {Address (Street Address):9.1}, {Address (City):9.3}, {Address (State / Province / Region):9.4}  {Address (ZIP / Postal Code):9.5}</td>
</tr>
<tr>
<td><strong>Company License Number(s):</strong>        {company_license_numbers:10}</td>
</tr>
<tr>
<td><strong>Business Type:</strong> {business-type:79}</td>
</tr>
</tbody>
</table>
<table width="100%" cellpadding="5">
<tbody>
<tr>
<td><strong>Number of years in business:</strong>        {years_in_business:11}</td>
<td><strong>FEIN #:</strong>   {fein:12}</td>
</tr>
</tbody>
</table>
<table width="100%" cellpadding="5">
<tbody>
<tr>
<td><strong>Effective Date Desired:</strong>        {from:13} to        {to:14}</td>
</tr>
<tr>
<td>
<h4>Limits of Liability</h4>
</td>
</tr>
<tr>
<td><strong>Occurrence:</strong>        ${occurrence:15}</td>
</tr>
<tr>
<td><strong>Products/Completed Operations:</strong>        ${products_completed_operations:17}</td>
</tr>
<tr>
<td><strong>Aggregate:</strong>        ${aggregate:18}</td>
</tr>
<tr>
<td>
<div style="text-align: center;"><strong>****Very important****<br /> The carrier will not allow a quote to be released until they have reviewed your company's contract.<br /> Please return with application. The "limitation of liability" or "liquidated damages" must be legible.</strong></div>
</td>
</tr>
</tbody>
</table>
<table width="100%" cellpadding="5">
<tbody>
<tr>
<td style="text-align: center; width: 100%;background: #ffc10d;padding:10px;">
<h2>Section II - Total Estimated Annual Revenue</h2>
</td>
</tr>
<tr>
<td><strong>Estimated Revenue for next 12 months (not including monitoring revenue):</strong>        {estimated_revenue:19}</td>
</tr>
<tr>
<td><strong>Estimated monitoring revenue:</strong>        {estimated_monitoring_revenue:20}</td>
</tr>
<tr>
<td><strong>% of revenue generated by jobs subcontracted to insured companies:</strong>        {revenue_generated_by:21}</td>
</tr>
<tr>
<td><strong>Number of technicians not including owner:</strong>        {number_of_technicians:22}</td>
</tr>
<tr>
<td><strong>Annual payroll for technicians not including clerical/admin/owner(s):</strong>        {annual_payroll:23}</td>
</tr>
<tr>
<td><strong>Revenue for previous 12 months:</strong>        {revenue_12_months:24}</td>
</tr>
<tr>
<td><strong>Owner(s) payroll (only if Field Work is performed by owner(s))</strong>        {owners_payroll:25}</td>
</tr>
</tbody>
</table>
<table width="100%" cellpadding="5">
<tbody>
<tr>
<td style="text-align: center; width: 100%;background: #ffc10d;padding:10px;">
<h2>Section III - Current Insurance Information</h2>
</td>
</tr>
</tbody>
</table>
<table width="100%" cellpadding="5">
<tbody>
<tr>
<td><strong>Carrier:</strong>        {carrier:26}</td>
<td><strong>Expiration Date:</strong>        {expiration_date:27}</td>
</tr>
<tr>
<td><strong>General Aggregate:</strong>        {general_aggregate:28}</td>
<td><strong>Occurrence:</strong>        </td>
</tr>
</tbody>
</table>
<strong>Claim History (Please provide 5 years current valued loss runs):</strong>
<table width="100%" cellpadding="5">
<tbody>
<tr>
<td><strong>Prior Year:</strong> {prior_year:29}</td><td><strong>1st Prior Year:</strong>        {1st_prior_year:30}</td>
</tr>
<tr>
<td><strong>2nd Prior Year:</strong>  {2nd_prior_year:31}</td><td><strong>3rd Prior Year:</strong>        {3rd_prior_year:32}</td>
</tr>
<tr>
<td><strong>4th Prior Year:</strong>        {4th_prior_year:33}</td><td></td>
</tr>
<tr>
<td><strong>Premium</strong>        {premium:34}</td><td></td>
</tr>
</tbody>
</table>
<!-- Basic Page Break -->
<pagebreak/>
<table width="100%" cellpadding="5">
<tbody>
<tr>
<td style="text-align: center; width: 100%;background: #ffc10d;padding:10px;">
<h2>Section IV - Operations</h2>
</td>
</tr>
<tr>
<td><strong>Do you operate in any other states?</strong>        {operate_in_any_other_states:35}</td>
</tr>
<tr>
<td><strong>If yes, please list:</strong>  {if_yes_please_list:36}</td>
</tr>
<tr>
<td>
<h4>Operations are:</h4>
</td>
</tr>
</tbody>
</table>
<table cellpadding="5">
<tbody>
<tr>
<td>{fire_alarm:37} <strong>% Fire Alarm</strong></td>
<td>{burglar_alarm:38} <strong>% Burglar Alarm</strong></td>
<td>{combination:39} <strong>% Combination</strong></td>
<td>{home_theater:40} <strong>% Home Theater</strong></td>
</tr>
<tr>
<td>{medical_alert:41}  <strong>% Medical Alert</strong></td>
<td>{temp_control:42}  <strong>% Temp. Control</strong></td>
<td colspan="2">{closed_circuit:43} <strong>% Closed Circuit</strong></td>
<td></td>
</tr>
<tr>
<td colspan="2">{preconstruction_wiringconduit:44}<strong>Preconstruction Wiring/Conduit</strong></td>
<td>{percent_other:45}<strong>% Other</strong></td>
<td></td>
</tr>
</tbody>
</table>
<table width="100%" cellpadding="5">
<tbody>
<tr>
<td>
<h4>Client Base:</h4>
</td>
</tr>
</tbody>
</table>
<table cellpadding="5">
<tbody>
<tr>
<td>{commercial:46} <strong>% Commercial</strong></td>
<td>{apartments:47} <strong>% Apartments</strong></td>
<td>{industrial:48} <strong><strong>% Industrial</strong></strong></td>
<td>{single_family:49} <strong>% Single Family</strong></td>
</tr>
<tr>
<td>{institutional:50} <strong>% Institutional</strong></td>
<td>{condos:51} <strong>% Condos</strong></td>
<td colspan="2">{new_home_builders:52} <strong>% New Home Builders</strong></td>
</tr>
</tbody>
</table>
<table width="100%" cellpadding="5">
<tbody>
<tr>
<td>** Please describe the type of work being done for New Home Builders i.e. tract homes, condominiums, custom homes. A "tract home" is defined as a development of five or more individual and freestanding houses which share common or similar design elements, floor plans, blueprints and/or architectural details, and/or which are constructed at the same time, or consecutively, on the same parcel, adjacent parcels, or parcels so located within one geographic area to be considered a single project.**</td>
</tr>
<tr>
<td><strong>Description:</strong>        {description-work:53}</td>
</tr>
<tr>
<td>** If a portion of the work you are doing for new home builders is for tract homes or condos and another portion is for custom homes, please provide percentages for each(must equal 100%)**</td>
</tr>
</tbody>
</table>
<table width="100%" cellpadding="5">
<tbody>
<tr>
<td><strong>Tract homes, Condos, Townhouses:</strong>        {tract_homes_condos_townhouses:54}</td>
<td><strong>Custom Homes</strong>        {custom_homes:55}</td>
</tr>
<tr>
<td><strong>Total Number of Customers:</strong>        {total_number_of_customers:56}</td>
<td><strong>Number under contract:</strong>        {number_under_contract:57}</td>
</tr>
<tr>
<td colspan="2"><strong>Do you install alarm or service safety equipment in:</strong></td>
</tr>
</tbody>
</table>
<table width="100%" cellpadding="5">
<tbody>
<tr>
<td><strong>Nursing Homes</strong>        {nursing_homes:58}</td>
<td><strong>Medical Facilities</strong>        {medical_facilities:59}</td>
</tr>
<tr>
<td><strong>Correctional Facilities</strong>        {correctional_facilities:60}</td>
<td><strong>Detention Facilities</strong>        {detection_facilities:61}</td>
</tr>
<tr>
<td colspan="2"><strong>If yes, what percentage of your total work is designated to this?</strong>        {percentage_of_work:62}</td>
</tr>
<tr>
<td colspan="2"><strong>Does your company do its own monitoring?</strong>        {do_own_monitoring:63}</td>
</tr>
<tr>
<td colspan="2"><strong>If no, please provide the name of monitoring company detection facilities:</strong>        {monitoring_company:64}</td>
</tr>
</tbody>
</table>
<table width="100%" cellpadding="5">
<tbody>
<tr>
<td style="text-align: center; width: 100%;background: #ffc10d;padding:10px;">
<h2>Section V - Alarm Response</h2>
</td>
</tr>
<tr>
<td><strong>Do you provide security/patrol response to your customers if and when Police/Fire/EMT's do not respond?</strong>        {data:securitypatrol_response:65}</td>
</tr>
<tr>
<td><strong>If yes, are the responders employees, or hired/contracted for this service?</strong>        {hiredcontracted_for_this_service:66}</td>
</tr>
<tr>
<td><strong>Fully describe alarm response procedures:</strong>        {alarm_response_procedures:67}</td>
</tr>
<tr>
<td><strong>If responders are not employees, do you have a written contract with the security company that provides the response?</strong>        {written_contract:68}</td>
</tr>
<tr>
<td><strong>If you have a contract with the security company, is either part holding the other harmless/providing indemnification?</strong>        {indemnification:69}</td>
</tr>
<tr>
<td><strong>If yes, provide details:</strong>        {details-indemn:70}</td>
</tr>
<tr>
<td><strong>Do any employees or subcontractors carry firearms?</strong>        {carry_firearms:71}</td>
</tr>
<tr>
<td><strong>Completed By:</strong>        {completed_by:72}      <strong>Title:</strong>        {title-comp:73}</td>
</tr>
<tr>
<td><strong>Date:</strong>        {date113:74}</td>
</tr>
<tr>
<td><strong>Signature:</strong>        <img src={signature:93}></td>
</tr>
</tbody>
</table>
